services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - uat_network
    env_file:
      - .env

networks:
  uat_network:
    external: true