services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - 3k_uat_network
    container_name: frontend-uat
    env_file:
      - .env

networks:
  3k_uat_network:
    external: true