services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - frontend3k
    env_file:
      - .env

networks:
  frontend3k:
    driver: bridge