import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthProviders from "../components/providers/AuthProviders";
import UIProviders from "@/components/providers/UIProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "3 Kings",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.webp",
      type: "image/webp",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          <UIProviders>
            {children}
          </UIProviders>
        </AuthProviders>
      </body>
    </html>
  );
}
