import type { Metadata } from 'next';

import localFont from 'next/font/local';

import Nav from '@/components/nav/nav';
import Footer from '@/components/footer/footer';
import './globals.css';

import AuthProviders from '../components/providers/AuthProviders';
import UIProviders from '@/components/providers/UIProviders';

import auth from '@/libs/auth';

const KMITL2020 = localFont({ src: '../../public/fonts/KMITL 2020 Regular.woff2' });

export const metadata: Metadata = {
  title: '3 Kings',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/images/logo.webp',
      type: 'image/webp',
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="../images/logo.webp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${KMITL2020.className} antialiased`}>
        <AuthProviders>
          <UIProviders>
            <Nav session={session} />
            {children}
          </UIProviders>
        </AuthProviders>
        <Footer />
      </body>
    </html>
  );
}
